version: '3.9'

services:
  agri-django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agri-django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      conda run --no-capture-output -n agri 
      python manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
